[André] Removing password request from API Create User
richardnikolas/magma-safe-backend pull request #16
Opened 2021-04-04 22:04 UTC by lDede

I let the password value empty on INSERT due the 'password' on table 'User' on DB.

2021-04-04 22:27 UTC, richardnikolas requested changes
Checar os comentários

2021-04-04 22:27 UTC, richardnikolas commented on MagmaSafe.Borders/Dtos/User/CreateUserRequest.cs
> +        public bool IsActive { get; set; } = false;
Pode remover essa linha, não faz sentido. Na hora da criação do usuário ele **sempre** vai estar ativo.

2021-04-04 22:27 UTC, richardnikolas commented on MagmaSafe.Repositories/SQLStatements/UserStatements.cs
> +                @Id, @Name, @Email, '', @IsAdmin, @IsActive
Remover completamente

```suggestion
                @Id, @Name, @Email, @IsAdmin, @IsActive
```

2021-04-04 22:55 UTC, lDede commented on MagmaSafe.Borders/Dtos/User/CreateUserRequest.cs
> +        public bool IsActive { get; set; } = false;
Linha removida

2021-04-04 22:55 UTC, lDede commented on MagmaSafe.Repositories/SQLStatements/UserStatements.cs
> +                @Id, @Name, @Email, '', @IsAdmin, @IsActive
Alteração efetuada

2021-04-04 23:07 UTC, richardnikolas commented
- Remover o atributo **Password** da Entity **User** também
- Remover a dependência **securityHelper** do arquivo UserRepository. Não está mais sendo usado.

2021-04-05 12:23 UTC, richardnikolas requested changes

2021-04-05 12:23 UTC, richardnikolas commented on MagmaSafe.Repositories/UserRepository.cs
>          private readonly IRepositoryHelper helper;
Era pra remover só o secutiry helper mano kkkk 

```suggestion
        private readonly IRepositoryHelper helper;

        public UserRepository(IRepositoryHelper helper)
        {
            this.helper = helper;
        }
```

2021-04-05 22:42 UTC, richardnikolas reviewed
Beleza, agora a gente só podia arrumar esses seus commits antes de mergear o PR.

2021-04-06 00:37 UTC, richardnikolas approved these changes

2021-04-06 00:38 UTC, merged